theme: jekyll-theme-cayman
title: "Cientopolis blog"
description: "The English blog of the Cientopolis project. You can see the full version in Spanish at http://cientopolis.org."

twitter_username:     cientopolis
github_username:      cientopolis
facebook_username:    cientopolis
