theme: jekyll-theme-cayman
title: "Cientopolis blog"
description: "The English blog of the Cientopolis project. You can see the full version in Spanish at http://cientopolis.org."

# Staticman comments
staticmanUrl: https://api.staticman.net/v3/entry/github/cientopolis/cientopolis.github.io/master/comments
